/**
 * ZeroTierCentralAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of GlobalPermissions
 *
 * @constructor
 */
angular.module('ZeroTierCentralAPILib')
    .factory('GlobalPermissions', ['BaseModel',
        function (BaseModel) {
            var GlobalPermissions = function (obj) {
                if (!obj) {
                    this.r = null;
                    this.m = null;
                    this.d = null;
                    this.a = null;
                    this.o = null;
                } else {
                    this.r = obj.r;
                    this.m = obj.m;
                    this.d = obj.d;
                    this.a = obj.a;
                    this.o = obj.o;
                }
            }
    
            GlobalPermissions.prototype = new BaseModel();
            GlobalPermissions.prototype.constructor = GlobalPermissions;
        
            /**
             * Read
             *
             * @return {bool|null}
             */
            GlobalPermissions.prototype.getR = function () {
                return this.r;
            };
        
            /**
             * Setter for R
             * 
             * @param {bool|null} value 
             */
            GlobalPermissions.prototype.setR = function (value) {
                this.r = value;
            };
        
            /**
             * Modify
             *
             * @return {bool|null}
             */
            GlobalPermissions.prototype.getM = function () {
                return this.m;
            };
        
            /**
             * Setter for M
             * 
             * @param {bool|null} value 
             */
            GlobalPermissions.prototype.setM = function (value) {
                this.m = value;
            };
        
            /**
             * Delete
             *
             * @return {bool|null}
             */
            GlobalPermissions.prototype.getD = function () {
                return this.d;
            };
        
            /**
             * Setter for D
             * 
             * @param {bool|null} value 
             */
            GlobalPermissions.prototype.setD = function (value) {
                this.d = value;
            };
        
            /**
             * Authorize
             *
             * @return {bool|null}
             */
            GlobalPermissions.prototype.getA = function () {
                return this.a;
            };
        
            /**
             * Setter for A
             * 
             * @param {bool|null} value 
             */
            GlobalPermissions.prototype.setA = function (value) {
                this.a = value;
            };
        
            /**
             * Owner
             *
             * @return {bool|null}
             */
            GlobalPermissions.prototype.getO = function () {
                return this.o;
            };
        
            /**
             * Setter for O
             * 
             * @param {bool|null} value 
             */
            GlobalPermissions.prototype.setO = function (value) {
                this.o = value;
            };
        
            return GlobalPermissions;
        }
    ]);

}(angular));
