/**
  * ZeroTierCentralAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('ZeroTierCentralAPILib')
    .factory('MemberController', ['$q', 'Configuration', 'HttpClient', 'APIHelper', 'Member',
        function($q, Configuration, HttpClient, APIHelper, Member) {
            return {
                /**
                 * Retrieve a Member
                 * @param {string} networkId    Required parameter: 16-digit ZeroTier network ID
                 * @param {string} nodeId    Required parameter: 10-digit ZeroTier node ID (a.k.a. ZeroTier address)
                 *
                 * @return {promise<Member>}
                 */
                retrieveAMember: function (networkId, nodeId) {

                    //Create promise to return
                    var _deffered = $q.defer();
                    
                    //prepare query string for API call
                    var _baseUri = Configuration.BASEURI
                    var _queryBuilder = _baseUri + "/api/network/{networkId}/member/{nodeId}";
                    
                    // Process template parameters
                    _queryBuilder = APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
                        'networkId': networkId,
                        'nodeId': nodeId
                    });

                    //validate and preprocess url
                    var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                    
                    // prepare headers
                    var _headers = {
                        'accept': 'application/json'
                    };

                    // prepare and invoke the API call request to fetch the response
                    var _config = {
                        method: "GET",
                        queryUrl: _queryUrl,
                        headers: _headers,
                        username: Configuration.basicAuthUserName,
                        password: Configuration.basicAuthPassword,
                    };
                    
                    var _response = HttpClient(_config);
                    
                    //process response
                    _response.then(function (_result) {
                        var _strResult =_result.body;
                        _result.body = new Member(_strResult);
                        _deffered.resolve(_result);
                    }, function(_result){
                        // Error handling for custom HTTP status codes
                        _deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: _result.code, errorResponse: _result.message}, _result.getContext()));
                    });
                    
                    return _deffered.promise;
                },
                /**
                 * Update or add a Member
                 * @param {string} networkId    Required parameter: 16-digit ZeroTier network ID
                 * @param {string} nodeId    Required parameter: 10-digit ZeroTier node ID (a.k.a. ZeroTier address)
                 * @param {Member} body    Required parameter: Example:
                 *
                 * @return {promise<Member>}
                 */
                updateOrAddAMember: function (networkId, nodeId, body) {

                    //Create promise to return
                    var _deffered = $q.defer();
                    
                    //prepare query string for API call
                    var _baseUri = Configuration.BASEURI
                    var _queryBuilder = _baseUri + "/api/network/{networkId}/member/{nodeId}";
                    
                    // Process template parameters
                    _queryBuilder = APIHelper.appendUrlWithTemplateParameters(_queryBuilder, {
                        'networkId': networkId,
                        'nodeId': nodeId
                    });

                    //validate and preprocess url
                    var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                    
                    // prepare headers
                    var _headers = {
                        'accept': 'application/json',
                        'content-type': 'application/json; charset=utf-8'
                    };

                    // Remove null values
                    APIHelper.cleanObject(body);

                    // prepare and invoke the API call request to fetch the response
                    var _config = {
                        method: "POST",
                        queryUrl: _queryUrl,
                        headers: _headers,
                        username: Configuration.basicAuthUserName,
                        password: Configuration.basicAuthPassword,
                        body: body
                    };
                    
                    var _response = HttpClient(_config);
                    
                    //process response
                    _response.then(function (_result) {
                        var _strResult =_result.body;
                        _result.body = new Member(_strResult);
                        _deffered.resolve(_result);
                    }, function(_result){
                        // Error handling for custom HTTP status codes
                        _deffered.reject(APIHelper.appendContext({errorMessage:"HTTP Response Not OK", errorCode: _result.code, errorResponse: _result.message}, _result.getContext()));
                    });
                    
                    return _deffered.promise;
                }
            }
        }
    ]);

}(angular));
