/**
 * ZeroTierCentralAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Permissions
 *
 * @constructor
 */
angular.module('ZeroTierCentralAPILib')
    .factory('Permissions', ['BaseModel', 'MId',
        function (BaseModel, MId) {
            var Permissions = function (obj) {
                if (!obj) {
                    this.mId = null;
        
                    // Append to variable dictionary
                    this._variableDict['mId'] = '{id}';
                } else {
                    this.mId = new MId(obj.{id});
            
                    // Append to variable dictionary
                    this._variableDict['mId'] = '{id}';
                }
            }
    
            Permissions.prototype = new BaseModel();
            Permissions.prototype.constructor = Permissions;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {MId|null}
             */
            Permissions.prototype.getMId = function () {
                return this.mId;
            };
        
            /**
             * Setter for MId
             * 
             * @param {MId|null} value 
             */
            Permissions.prototype.setMId = function (value) {
                this.mId = value;
            };
        
            return Permissions;
        }
    ]);

}(angular));
