/**
 * ZeroTierCentralAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of RandomToken
 *
 * @constructor
 */
angular.module('ZeroTierCentralAPILib')
    .factory('RandomToken', ['BaseModel',
        function (BaseModel) {
            var RandomToken = function (obj) {
                if (!obj) {
                    this.token = null;
                    this.clock = null;
                    this.raw = null;
                } else {
                    this.token = obj.token;
                    this.clock = obj.clock;
                    this.raw = obj.raw;
                }
            }
    
            RandomToken.prototype = new BaseModel();
            RandomToken.prototype.constructor = RandomToken;
        
            /**
             * Random string suitable for use as an API authentication token
             *
             * @return {string|null}
             */
            RandomToken.prototype.getToken = function () {
                return this.token;
            };
        
            /**
             * Setter for Token
             * 
             * @param {string|null} value 
             */
            RandomToken.prototype.setToken = function (value) {
                this.token = value;
            };
        
            /**
             * Current server-side system clock (ms since epoch)
             *
             * @return {double|null}
             */
            RandomToken.prototype.getClock = function () {
                return this.clock;
            };
        
            /**
             * Setter for Clock
             * 
             * @param {double|null} value 
             */
            RandomToken.prototype.setClock = function (value) {
                this.clock = value;
            };
        
            /**
             * Raw random bytes in hex format
             *
             * @return {string|null}
             */
            RandomToken.prototype.getRaw = function () {
                return this.raw;
            };
        
            /**
             * Setter for Raw
             * 
             * @param {string|null} value 
             */
            RandomToken.prototype.setRaw = function (value) {
                this.raw = value;
            };
        
            return RandomToken;
        }
    ]);

}(angular));
